---
title: "MA677Assignment1"
author: "Max Liu"
date: "2/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
#install.packages("ISLR")
library(ISLR)
library(boot)
library(pwr2)
```
###Ch3-<p102>  
##To prove the m is in the range of [69, 73]  
According to the paragraphs on page 102, the desired significant level is 0.05  
Given:  
$$z =\frac{\hat{p}-p_o}{\sqrt{\frac{p_o(1-p_o)}{n}}}$$  
While $$z = \pm 1.65$$  

We have:  
1)
```{r}
n=100
#p_hat
p_hat = 1.65 * sqrt(0.6*0.4) / 10 +0.6
p_hat
#m
m = p_hat*n
head(m)
```
And:  
2)
```{r}
#p_hat
p_hat = -1.65 * sqrt(0.8*0.2) / 10 +0.8
p_hat
#m
m = p_hat*n
head(m)
```

##To illustrate in Power Curve
We have \alpha = 0.05  
Critical Value = m = 1)69; 2)73  
n = 100 

```{r}
p.a = seq(0.4, 1, by=.01)
p.rej_1 = 1 - pbinom(69, 100, p.a)
p.rej_2 = 1 - pbinom(73, 100, p.a)
plot(p.a, p.rej_1, type="l", main="Power Curve")
par(new = TRUE)
plot(p.a, p.rej_2, type="l", main="Power Curve")
 rect(xleft=0.6, ybottom=0.05, xright=0.8, ytop=0.95, lty=4)
```






